version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 --timeout 600 manage:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - litscan-prefer_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  litscan-prefer_postgres_data:
    external: true